config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :users
  resources :submissions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "submissions#new"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#login'
  get '/logout',  to: 'sessions#logout'
  get "submissions/category/:category_id", to: "submissions#get_submissions"
  post "/send_message", to: "users#send_message"
  post "/select_candidates", to: "users#select_candidates"
  get "/select_candidates", to: "users#select_candidates"
  post "/set_difficulty_level", to: "users#set_difficulty_level"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  before_action :authorize_admin, only: [:show]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @submissions = Submission.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def send_message
    number_of_errors = DifficultyLevel.find_by(name: params[:difficulty_level])&.number_of_errors || 0

    successful_candidates = if params[:message_checkbox]
      Submission.where("#{params[:broadcast_method]}_sent": "NO").select { |s| s.shortlisted?(number_of_errors) }
    else
      Submission.all.select { |s| s.shortlisted?(number_of_errors) }
    end

    if (successful_candidates.size == 0)
      flash[:danger] = "Message not sent. No successful candidates detected."
      redirect_to root_path
    else
      if params[:broadcast_method] == "sms"
        SendSmsJob.perform_later(successful_candidates, params[:message])
      else
        SendEmailJob.perform_later(successful_candidates, params[:message])
      end

      flash[:success] = "Message successfully sent"
      redirect_to root_path
    end
  end

  def select_candidates
    @submissions = Submission.all
    number_of_errors = DifficultyLevel.find_by(name: "hard")&.number_of_errors || 0
    if params[:difficulty_level]&.to_i == 0
      number_of_errors = DifficultyLevel.find_by(name: "medium")&.number_of_errors || 2
    elsif params[:difficulty_level]&.to_i == -1
      number_of_errors = DifficultyLevel.find_by(name: "easy")&.number_of_errors || 5
    end

    if params[:candidate_type].to_i == 0
      @submissions = Submission.all.select { |s| s.shortlisted?(number_of_errors) }
    end

    if params[:candidate_type].to_i == -1
      @submissions = Submission.all.reject { |s| s.shortlisted?(number_of_errors) }
    end

    render "show"
  end

  def set_difficulty_level
    ["hard", "medium", "easy"].each do |d|
      level = DifficultyLevel.find_by(name: d)
      if level.nil?
        DifficultyLevel.new(name: d, number_of_errors: params[d.to_sym]).save!
      else
        level.update(number_of_errors: params[d.to_sym])
      end
    end

    flash[:success] = "Settings successfully saved"
    redirect_to root_path
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def authorize_admin
    unless is_admin?
      redirect_to root_path
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password, :role)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_article_review_modal.html.erb
<div class="modal fade" id=<%= "article_review_#{submission.id}" %> tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
          <p class="modal-title"><%= submission.first_name %> <%= submission.last_name %></p>
        </div>
        <div class="modal-body">
          <div class="candidate-passport text-right">
            <%= image_tag(url_for(submission.image), class: "pull-right img-responsive") if submission.image.attachment %>
          </div>
          <div class="article">
            <%= submission.article %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-sm btn-outline-dark modal-close" data-dismiss="modal">Close</button>
            <% if submission.article_file.attachment %>
              <%= link_to "Download", rails_blob_path(submission.article_file, disposition: 'attachment'), class: "btn btn-sm btn-outline-primary modal-submit" %>
            <% end %>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/users/_candidates_select_modal.html.erb
<div class="modal fade" id="select_candidates" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
        <%= form_with(url: "/select_candidates", local: true) do %>
        <div class="modal-body">
            <div class="form-group">
              <select name="candidate_type" class="form-control" id="candidates-select" required="true">
                <option value="1">All candidates</option>
                <option value="0" selected>Successful candidates</option>
                <option value="-1">Unsucessful candidates</option>
              </select>
            </div>
            <div class="form-group">
              <select name="difficulty_level" class="form-control" id="difficulty-level" required="true">
                <option value="1">Hard</option>
                <option value="0">Medium</option>
                <option value="-1">Easy</option>
              </select>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-sm btn-outline-dark modal-close" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-sm btn-outline-primary modal-submit">Submit</button>
            </div>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/users/_difficulty_level_modal.html.erb
<div class="modal fade" id="difficulty_level" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
        <%= form_with(url: "/set_difficulty_level", local: true) do %>
        <div class="modal-body">
            <div class="form-group">
              <label><b>Hard</b> <%= "(Current Value: #{DifficultyLevel.find_by(name: 'hard')&.number_of_errors || 0})" %></label>
              <select name="hard" class="form-control" required="true">
                <option value="">--Maximum number of grammatical errors--</option>
                <option value="0">0</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
              </select>
            </div>
            <div class="form-group">
              <label><b>Medium</b> <%= "(Current Value: #{DifficultyLevel.find_by(name: 'medium')&.number_of_errors || 2})" %></label>
              <select name="medium" class="form-control" required="true">
                <option value="">--Maximum number of grammatical errors--</option>
                <option value="0">0</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                <option value="10">10</option>
              </select>
            </div>
            <div class="form-group">
              <label><b>Easy</b> <%= "(Current Value: #{DifficultyLevel.find_by(name: 'easy')&.number_of_errors || 5})" %></label>
              <select name="easy" class="form-control" required="true">
                <option value="">--Maximum number of grammatical errors--</option>
                <option value="0">0</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                <option value="10">10</option>
                <option value="11">11</option>
                <option value="12">12</option>
                <option value="13">13</option>
                <option value="14">14</option>
                <option value="15">15</option>
              </select>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-sm btn-outline-dark modal-close" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-sm btn-outline-primary modal-submit">Save</button>
            </div>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.text_field :email, class: "form-control", placeholder: "Enter your email" %>
  </div>

  <div class="field">
    <%= form.password_field :password, class: "form-control" %>
  </div>

  <button type="submit" class="btn btn-outline-primary">Login</button>
<% end %>

app/views/users/_message_modal.html.erb
<div class="modal fade" id="order" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h6 class="modal-title">Send messages to successful candidates</h6>
      </div>
        <%= form_with(url: "/send_message", local: true) do %>
        <div class="modal-body">
            <div class="form-group">
              <select name="difficulty_level" class="form-control" required="true">
                <option value="">--Select Difficulty Level--</option>
                <option value="hard">Hard</option>
                <option value="medium">Medium</option>
                <option value="easy">Easy</option>
              </select>
            </div>
            <div class="form-group">
              <select name="broadcast_method" class="form-control" required="true" id="broadcast-method">
                <option value="">--Broadcast Method--</option>
                <option value="email">Email</option>
                <option value="sms">SMS</option>
              </select>
            </div>
            <div class="form-group">
              <textarea name="message" type="text" class="form-control address-input" placeholder="Write message" rows="5" required></textarea>
            </div>
            <div class="form-group">
              <div class="form-check">
                <input class="form-check-input" type="checkbox" id="gridCheck" name="message_checkbox">
                <label class="form-check-label" for="gridCheck" id="message-checkbox-label">
                  Send to only candidates that have not recieved message
                </label>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-sm btn-outline-dark modal-close" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-sm btn-outline-primary modal-submit">Send</button>
            </div>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="user-login">
  <h3>Login</h3>

  <%= render 'form', user: @user %>

  <%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<% provide(:title, "Admin Dashboard") %>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <button class="close" data-dismiss="alert">×</button>
    <%= value %>
  </div>
<% end %>
<div class="main">
  <div class="row">

    <div class="side-bar col-md-2">
      <div class="side-button">
        <span id="number-of-candidates"><%= pluralize(@submissions.size,"candidate") if @submissions %></span>
        <a href="#" data-toggle="modal" data-target="#select_candidates" class="btn btn-warning btn-sm select-candidates">Select Candidates</a>
        <a href="#" data-toggle="modal" data-target="#difficulty_level" class="btn btn-warning btn-sm">Set Difficulty Level</a>
        <a href="#" data-toggle="modal" data-target="#order" class="btn btn-warning btn-sm send-msg-btn">Send message</a>
      </div>
      <div class="logout">
        <%= link_to 'Logout', logout_path, class: "admin-login btn btn-outline-dark" %>
      </div>
    </div>
    <div class="main-side col-md-10">
        <div class="main-side-title">
          <h3>Admin Dashboard</h3>
        </div>

        <div class="table-container">
          <table class="table">
            <thead class="thead-light" id="submissions-head">
              <tr>
                <th scope="col">First name</th>
                <th scope="col">Last name</th>
                <th scope="col">School</th>
                <th scope="col">DOB</th>
                <th scope="col">Class</th>
                <th scope="col">Phone no</th>
                <th scope="col"># of errors</th>
                <th scope="col">Email sent</th>
                <th scope="col">SMS sent</th>
              </tr>
            </thead>
            <tbody id="submissions-body">
            <% @submissions.each do |s| %>
              <%= render "users/article_review_modal.html", submission: s %>
              <tr data-toggle="modal" data-target=<%= "#article_review_#{s.id}" %>>
                <td><%= s.first_name %></td>
                <td><%= s.last_name %></td>
                <td><%= s.school %></td>
                <td><%= s.date_of_birth %></td>
                <td><%= s.candidate_class.split("_").join(" ").upcase %></td>
                <td><%= s.phone_number %></td>
                <td><%= s.number_of_errors %></td>
                <td><%= s.email_sent %></td>
                <td><%= s.sms_sent %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
    </div>
  </div>
</div>