config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :users
  resources :submissions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "submissions#new"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#login'
  get '/logout',  to: 'sessions#logout'
  get "submissions/category/:category_id", to: "submissions#get_submissions"
  post "/send_message", to: "users#send_message"
  post "/select_candidates", to: "users#select_candidates"
  get "/select_candidates", to: "users#select_candidates"
  post "/set_difficulty_level", to: "users#set_difficulty_level"
end

app/models/submission.rb
class Submission < ApplicationRecord
  has_one_attached :image
  has_one_attached :article_file
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :candidate_class, presence: true
  validates :school, presence: true
  validates :email, uniqueness: true, format: { with: /\A[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/, message: "must be valid"}
  validates :phone_number, uniqueness: true, format: { with: /\A\d{11}\z/, message: 'must be valid'}
  validate :check_article_presence
  validate :filter_article_words
  validate :check_image_presence

  after_commit :update_number_of_errors, on: :create

  def filter_article_words
    article_size = article.split.size
    if (article_size < 50) || (article_size > 500)
    # if (article_size < 2) || (article_size > 20)
      errors.add(:base, "Article should contain between 50-500 words, but you submitted #{article_size} words.")
    end
  end

  def check_image_presence
    if image.attachment == nil
      errors.add(:base, "Your passport must be added")
    elsif (image.blob.byte_size/1000) > 500
      errors.add(:base, "Your passport can not be greater than 500kb")
    end
  end

  def check_article_presence
    unless article.present?
      errors.add(:base, "Please select your article")
    end
  end

  def shortlisted?(no_of_errors)
    (number_of_errors <= no_of_errors) && (age >= 18) && (candidate_class == "jss_3")
  end

  def age
    ((Time.zone.now - date_of_birth.to_time) / 1.year.seconds).floor
  end

  def update_number_of_errors
    # first_part_of_article = article.truncate(500, separator: '.')
    # no_of_errors = check_grammatical_errors(first_part_of_article)["corrections"].count
    # no_of_errors += check_grammatical_errors(article[(first_part_of_article.size - 1)..article.size].truncate(500, separator: '.'))["corrections"].count

    # self.update(number_of_errors: no_of_errors)
    SubmissionJob.perform_later(self)
  end

  # private

  # def check_grammatical_errors(text)
  #   parser = Gingerice::Parser.new
  #   parser.parse text
  # end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :update, :destroy]
  before_action :redirect_admin, only: [:new]

  # GET /submissions
  # GET /submissions.json
  def index
    @submissions = Submission.all
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
  end

  # def get_submissions
  #   submissions = Submission.all
  #   if params[:category_id].to_i == 0
  #     submissions = Submission.all.select { |s| s.shortlisted? }
  #   end

  #   if params[:category_id].to_i == -1
  #     submissions = Submission.all.reject { |s| s.shortlisted? }
  #   end

  #   render :json => submissions
  # end

  # GET /submissions/new
  def new
    @submission = Submission.new
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions
  # POST /submissions.json
  def create
    submission = Submission.new(submission_params)
    if submission.save
      redirect_to root_path
      flash[:success] = "Article successfully submitted"
    else
      submission_params.each do |name, value|
        cookies[name] = { :value => value, :expires => 2.seconds.from_now }
      end
      redirect_to root_path
      flash[:danger] = submission.errors.full_messages.first
    end
  end

  # PATCH/PUT /submissions/1
  # PATCH/PUT /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    def check_grammatical_errors(text)
      parser = Gingerice::Parser.new
      parser.parse text
    end

    def redirect_admin
      if is_admin?
        redirect_to user_path(current_user)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_params
      params.require(:submission).permit(:first_name, :middle_name, :last_name, :date_of_birth, :candidate_class, :school, :article, :email, :phone_number, :image, :article_file)
    end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_form.html.erb
<div class="form-container">
  <%= form_with(model: submission, local: true, html: {class:  "submit-form"}) do |form| %>

    <div class="file-upload">
      <label for="photo-input">
          <%= image_tag 'passport.png', class: 'hidden image_preview' %>
      </label>
      <%= form.file_field :image, class: "photo_upload", id: "photo-input" %>
    </div>
    <div class="passport-error-msg"></div>

    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= form.text_field :first_name, class: "form-control", required: true, value: cookies[:first_name], placeholder: "First Name" %>
        </div>
        <div class="form-group">
          <%= form.text_field :last_name, class: "form-control", required: true, value: cookies[:last_name], placeholder: "Last Name" %>
        </div>

        <div class="form-group">
          <%= form.select :candidate_class, [["JSS 1", "jss_1"], ["JSS 2", "jss_2"], ["JSS 3", "jss_3"], ["SSS 1", "sss_1"], ["SSS 2", "sss_2"], ["SSS 3", "sss_3"]], { prompt: "--Class--" }, { class: "form-control", required: true } %>
        </div>

        <div class="form-group">
          <%= form.email_field :email, class: "form-control", required: true, value: cookies[:email], placeholder: "Email Address" %>
        </div>
      </div>

      <div class="col-md-6">
        <div class="form-group">
          <%= form.text_field :middle_name, class: "form-control", value: cookies[:middle_name], placeholder: "Middle Name" %>
        </div>
        <div class="form-group">
          <%= form.text_field :school, class: "form-control", required: true, value: cookies[:school], placeholder: "School (Fullname and location)" %>
        </div>
        <div class="form-group">
          <%= form.text_field :phone_number, class: "form-control", placeholder: "e.g: 07065437832", required: true, value: cookies[:phone_number] %>
        </div>
        <div class="form-group dob">
          <%= form.date_field :date_of_birth, class: 'form-control', required: true, value: cookies[:date_of_birth], placeholder: "Date of Birth" %>
          <div class="dob-text"><small><em>Date of birth</em></small></div>
        </div>
      </div>
      <div class="col-md-12">
        <div class="form-group">
          <%= form.text_area :article, class: "form-control article-field", placeholder: "Write your article here", id: "article-text-area" %>
        </div>
      </div>

      <div class="col-md-12">
        <div class="form-group">
          <div class="upload-info">Select your article <small>(Note: Only .txt files are allowed)</small></div>
          <%= form.file_field :article_file, id: "article-input" %>
          <div class="article-file-error-msg"></div>
      </div>
      </div>
    </div>
    <div class="submit-button">
      <button type="submit" class="register-btn">Submit</button>
    </div>
  <% end %>
</div>

app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Submissions</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Middle name</th>
      <th>Last name</th>
      <th>Age</th>
      <th>Class</th>
      <th>School</th>
      <th>Article</th>
      <th>Email</th>
      <th>Mobile number one</th>
      <th>Mobile number two</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @submissions.each do |submission| %>
      <tr>
        <td><%= submission.first_name %></td>
        <td><%= submission.middle_name %></td>
        <td><%= submission.last_name %></td>
        <td><%= submission.age %></td>
        <td><%= submission.class %></td>
        <td><%= submission.school %></td>
        <td><%= submission.article %></td>
        <td><%= submission.email %></td>
        <td><%= submission.phone_number %></td>
        <td><%= submission.mobile_number_two %></td>
        <td><%= link_to 'Show', submission %></td>
        <td><%= link_to 'Edit', edit_submission_path(submission) %></td>
        <td><%= link_to 'Destroy', submission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Submission', new_submission_path %>

app/views/submissions/new.html.erb
<% provide(:title, "Home") %>


<div class="rows">
  <div class=" register-left">
    <div>
      <img class="img-logo" src="<%= asset_path('image.png') %>" alt="dagomo" />
      <h3>Welcome</h3>
      <p>Kindly fill this form to submit your article</p>
    </div>
    <% if params[:controller] == "users" && params[:action] == "show" %>
      <%= link_to "Logout", logout_path, class: "admin-login" %>
    <% else %>
      <span>Admin? <%= link_to 'Login here', login_path, class: "admin-login"%></span>
    <% end %>
  </div>
  <div class=" register-right">
    <% flash.each do |key, value| %>
     <div class="alert alert-<%= key %>">
       <button class="close" data-dismiss="alert">×</button>
       <%= value %>
     </div>
    <% end %>
    <div>
      <h4>DAOPECA Article</h4>
      <%= render 'form', submission: @submission %>
    </div>
  </div>
</div>

app/views/submissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @submission.first_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @submission.middle_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @submission.last_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @submission.age %>
</p>

<p>
  <strong>Class:</strong>
  <%= @submission.class %>
</p>

<p>
  <strong>School:</strong>
  <%= @submission.school %>
</p>

<p>
  <strong>Article:</strong>
  <%= @submission.article %>
</p>

<p>
  <strong>Email:</strong>
  <%= @submission.email %>
</p>

<p>
  <strong>Mobile number one:</strong>
  <%= @submission.phone_number %>
</p>

<p>
  <strong>Mobile number two:</strong>
  <%= @submission.mobile_number_two %>
</p>

<%= link_to 'Edit', edit_submission_path(@submission) %> |
<%= link_to 'Back', submissions_path %>